package ee.knowituniversity.gui;

import java.util.ArrayList;
import java.util.List;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import ee.knowituniversity.data.Course;
import ee.knowituniversity.data.Data;

public class CoursesPanel extends javax.swing.JPanel {

    private Data data;
    private AineTableModel tableModel;

    /**
     * Creates new form AineGUI
     *
     */
    public CoursesPanel() {
        initComponents();
    }

    public void setData(Data data) {
        this.data = data;
        List<Course> ained = new ArrayList<Course>();
        ained = data.getCoursesList();
        this.tableModel = new AineTableModel(ained);
        tableAined.setModel(tableModel);
//        tableAined.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
//
//            @Override
//            public void valueChanged(ListSelectionEvent e) {
//                if (e.getValueIsAdjusting()) {
//                    Course aine = tableModel.get(tableAined.getSelectedRow());
//                    if (aine != null) {
//                        updateAineId.setText(aine.getIdCourse()+ "");
//                        updateAineAineKood.setText(aine.getCourseCode());
//                        updateAineNimi.setText(aine.getName());
//                        updateAineOppejoud.setText(aine.getLecturer());
//                    }
//                }
//            }
//        });
    }
    
    

    private void eraseUpdateData() {
//        updateAineId.setText("");
//        updateAineAineKood.setText("");
//        updateAineNimi.setText("");
//        updateAineOppejoud.setText("");
    }
    
    private void change() {
        Course aine = tableModel.get(tableAined.getSelectedRow());
//        aine.changeValues( updateAineNimi.getText(), updateAineOppejoud.getText());
//        data.update(aine);
        tableModel.fireTableDataChanged();
        eraseUpdateData();
    }
    
    private void delete(){
        Course aine = tableModel.get(tableAined.getSelectedRow());
//        data.delete(aine);
        tableModel.remove(aine);
        eraseUpdateData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tableAined = new javax.swing.JTable();

        tableAined.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableAined);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableAined;
    // End of variables declaration//GEN-END:variables

}
