package ee.knowituniversity.gui;

import ee.knowituniversity.data.Data;
import ee.knowituniversity.generated.ObjectFactory;
import java.io.File;
import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Unmarshaller;

public class GUI extends javax.swing.JFrame {
    
    
    
    public GUI() {
        initComponents();
        try {
            JAXBContext jAXBContext = JAXBContext.newInstance(ObjectFactory.class.getPackage().getName());
//            InputStream stream = getClass().getClassLoader().getResourceAsStream("ee/knowituniversity/files/newGradesList.xml");
            File file = new File("xml/newGradesList.xml");
            Unmarshaller unmarshaller = jAXBContext.createUnmarshaller();
            ee.knowituniversity.generated.AllData generatedData = (ee.knowituniversity.generated.AllData) (unmarshaller.unmarshal(file));
            Data data = new Data(generatedData);
            data.generateAverageGrade();
            ainePanel1.setData(data);
            hinnePane1.setData(data);
            tudengiPane1.setData(data);
        } catch (JAXBException ex) {
            ex.printStackTrace();
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        ainePanel1 = new ee.knowituniversity.gui.CoursesPanel();
        hinnePane1 = new ee.knowituniversity.gui.HinnePane();
        tudengiPane1 = new ee.knowituniversity.gui.StudentsPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane2.addTab("Ained", ainePanel1);
        ainePanel1.getAccessibleContext().setAccessibleName("Ained");

        jTabbedPane2.addTab("Hinded", hinnePane1);
        jTabbedPane2.addTab("Opilane", tudengiPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 882, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jTabbedPane2.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GUI gui = new GUI();
                gui.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ee.knowituniversity.gui.CoursesPanel ainePanel1;
    private ee.knowituniversity.gui.HinnePane hinnePane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private ee.knowituniversity.gui.StudentsPane tudengiPane1;
    // End of variables declaration//GEN-END:variables
}
