package ee.knowituniversity.gui;

import ee.knowituniversity.data.Data;

public class HinnePane extends javax.swing.JPanel {
    
    private Data data;
    private GradeTableModel tableModel;

    /**
     * Creates new form HinnePane
     */
    public HinnePane() {
        initComponents();
    }

    public void setData(Data data) {
        this.data = data;
        this.tableModel = new GradeTableModel(data.getGradesList());
        tableAined.setModel(tableModel);
        txtAVG.setText(String.format("%.3f", data.getAverage()));
    }
    
    
    private void makeNew() {
//        Grade grade = new Grade(Integer.parseInt(txtAine.getText()), Integer.parseInt(txtTudengiKood.getText()), Integer.parseInt(txtHinne.getText()));
//        data.create(grade);
//        tableModel.add(grade);
//        txtAine.setText("");
//        txtTudengiKood.setText("");
//        txtHinne.setText("");
//        updateKHK(grade.getStudentCode().intValue());
    }
    
    private void updateKHK(int tudengikood) {
//        Student opilane = data.findeByStudentCode(tudengikood);
//        if (opilane != null) {
//            List<Grade> grades = data.findByStudentCode(tudengikood);
//            int counter = 0;
//            double hinne = 0;
//            for (Grade h : grades) {
//                Course aine = null;
//                aine = data.findByCourseId(h.getIdCourse());
//                if (aine == null) {
//                    System.err.println("Aine ei leitud");
//                    continue;
//                }
//                hinne += h.getGrade();
//                counter ++;
//            }
//            double KHK = hinne/counter;
//            System.out.println("Setting tudengi KHK = " + KHK);
//            opilane.setAvg(KHK);
//            opilane.setCourses(counter);
//            data.update(opilane);
//        }
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tableAined = new javax.swing.JTable();
        txtAVG = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        tableAined.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableAined);

        jLabel2.setText("AVG");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 292, Short.MAX_VALUE)
                .addComponent(txtAVG, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(266, 266, 266))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAVG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableAined;
    private javax.swing.JTextField txtAVG;
    // End of variables declaration//GEN-END:variables
}
