package ee.knowituniversity.gui;

import ee.knowituniversity.data.Data;

public class StudentsPane extends javax.swing.JPanel {
    
    private Data data;
    private StudentsTableModel tableModel;
    

    /**
     * Creates new form TudengiPane
     */
    public StudentsPane() {
        initComponents();
    }

    public void setData(Data data) {
        this.data = data;
        tableModel = new StudentsTableModel(data.getStudentsList());
        tableAined.setModel(tableModel);
//        tableAined.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
//
//            @Override
//            public void valueChanged(ListSelectionEvent e) {
//                if (e.getValueIsAdjusting()) {
//                    Student student = tableModel.get(tableAined.getSelectedRow());
//                    if (student != null) {
//                        txtIdUpdate.setText(student.getStudentCode()+ "");
//                        txtFirstNameUpdate.setText(student.getName()+ "");
//                        txtLastNameUpdate.setText(student.getLastName());
//                        txtKHKUpdate.setText(student.getAvgAsString());
//                    }
//                }
//            }
//        });
    }

    

    private void eraseUpdateData() {
//        txtIdUpdate.setText("");
//        txtIdUpdate.setText("");
//        txtFirstNameUpdate.setText("");
//        txtLastNameUpdate.setText("");
//        txtKHKUpdate.setText("");
    }

    private void makeNew() {
//        int tudengiKood = 0;
//        tudengiKood = data.getNewStudentCode();
//        Student student = new  Student(tudengiKood, txtEesnimi.getText(), txtPerenimi.getText());
//        data.create(student);
//        tableModel.add(student);
//        txtEesnimi.setText("");
//        txtPerenimi.setText("");
    }
//    
    private void change() {
//        Student opilane = tableModel.get(tableAined.getSelectedRow());
//        opilane.changeValues(txtFirstNameUpdate.getText(),  txtLastNameUpdate.getText());
//        data.update(opilane);
//        eraseUpdateData();
//        tableModel.fireTableDataChanged();
    }
    
    private void delete(){
//        Student opilane = tableModel.get(tableAined.getSelectedRow());
//        data.delete(opilane);
//        tableModel.remove(opilane);
//        eraseUpdateData();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tableAined = new javax.swing.JTable();

        tableAined.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableAined);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableAined;
    // End of variables declaration//GEN-END:variables
}
